name: lix
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - appdirs=1.4.3
  - asn1crypto
  - attrs=19.3.0
  - beautifulsoup4=4.8.2
  - black=19.10b0
  - bs4=4.8.2
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.0
  - coverage=5.0
  - cryptography=2.8
  - entrypoints=0.3
  - flake8=3.7.9
  - gevent=1.4.0
  - greenlet=0.4.15
  - grequests=0.4.0
  - idna=2.8
  - isort=4.3.21
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - mccabe=0.6.1
  - more-itertools=8.2.0
  - mypy=0.750
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - openssl=1.1.1d
  - packaging=20.1
  - pathspec=0.7.0
  - pip=20.0.2
  - pluggy=0.13.1
  - psutil=5.6.7
  - py=1.8.1
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pysocks=1.7.1
  - pytest=5.3.5
  - pytest-cov=2.8.1
  - python=3.8.1
  - python_abi=3.8
  - readline=7.0
  - regex=2020.1.8
  - requests=2.22.0
  - rope=0.16.0
  - setuptools=45.2.0
  - six=1.14.0
  - soupsieve=1.9.5
  - sqlite=3.31.1
  - tk=8.6.8
  - toml=0.10.0
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.1
  - urllib3=1.25.8
  - wcwidth=0.1.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11

